# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocables', '0003_auto_20171111_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testvocable',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocables', to='vocables.VocableTest'),
        ),
    ]
