# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 02:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocables', '0004_auto_20171111_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocablestats',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vocablestats',
            name='vocable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='vocables.Vocable'),
        ),
        migrations.AlterField(
            model_name='vocabletestanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vocabletestanswer',
            name='vocable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='vocables.TestVocable'),
        ),
    ]
