# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocables', '0005_auto_20171112_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabletestanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vocabletestanswer',
            name='solution',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
